### PR TITLE
Rm traps

### PR DESCRIPTION
**Pull request by BardurArantsson**
EDIT: For clarity:

Ok, so this is the merge with conflicts resolved. I think it would probably be simplest to just:

1. merge this into your branch
1. squash everything in the branch to a single commit
1. rebase on top of master.
1. force-push back to your rm-traps branch. (The PR will automatically be updated with the new commit.)

*IF* you want to keep the comments littered about in the old review, it might be safer to change that last step to push to a *NEW* branch, say rm-traps-v2,  and make a PR for that branch.

### CODE REVIEW

**Comment by BardurArantsson** [comment]
Btw, I've tested that it's possible to get through character creation, but nothing beyond that.

(Should be sufficient since all "my" conflicts were in the *.txt files)

**Comment by miramor** [comment]
Hmm. During rebase, I keep getting problems applying either the edit file change, or the largest chunk of trap removal. Not sure why, I'm probably doing something wrong...

**Comment by BardurArantsson** [comment]
Have you squashed everything to a single commit?

**Comment by miramor** [comment]
I attempted to do so, that's where it fails. Or is this a different command than git rebase? Just a minute.

**Comment by BardurArantsson** [comment]
You'll want to do

    git rebase -i 2a2527a68ff4fb909e8ad8a07c6e548d329e8588

and then just say "fixup" on each line.

**Comment by miramor** [comment]
Ah thanks. I was doing pick followed by squashes.

**Comment by miramor** [comment]
Nope, that's where it goes bad.

`error: could not apply 17b8094... Reformat flags in *.txt files to be more tool-friendly`

**Comment by BardurArantsson** [comment]
Ah, yes, my bad. Give me a few minutes, I'll figure out a simpler way to do this...

**Comment by BardurArantsson** [comment]
OK, here's a simpler way to do it. In your working directory, do:

    git branch rm-traps-v2 master
    git checkout rm-traps-v2
    git merge --squash rm-traps
    git commit -m "Remove traps"
    git push -u origin

(I'm assiming "origin" is your GitHub repository.)

Then you can just create a new PR for the new branch.

**Comment by miramor** [comment]
Just a minute, that somehow got merged into my master branch... ? N/M, that won't matter. I'll have the new PR up in a minute.

**Comment by miramor** [comment]
Done.

**Pull request merged**
